name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:

    - name: Set-up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ^1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Unit Test
      run: go test ./...
