name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Unit Test
      run: go test ./...

    # Add ignored packages to the `grep -v` segment
    - name: Vet
      run: go list ./... | grep -v 'antlrGen$' | while read -r line; do go vet "${line}"; done
