name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:

    - name: Set-up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.20

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Go generate
      run: go generate ./...

    - name: Unit Test
      run: go test ./...
